<<<<<<< HEAD
method: "tool"
max_steps: 5

model:
  path: openrouter/x-ai/grok-4-fast:free #path: "openrouter/meta-llama/llama-3.3-8b-instruct:free"
  method: "litellm"
  api_key: ${OPENROUTER_API_KEY}
  api_base: "https://openrouter.ai/api/v1"
  temperature: 0.7

tools:
  - name: add_numbers
    description: Add two numbers together
    target: src.agent.check.number.add_numbers

  - name: multiply
    description: Multiply two numbers
    target: src.agent.check.number.multiply

  - name: weather_tool
    description: Fetch live weather for a city
    target: src.agent.tool.weather.weather_tool

  - name: execute_sql
    description: Executes a SQL query against the database and returns the results.
    target: src.agent.check.sql_tool.execute_sql

  # - name: speech_text
  #   description: coverts speech to text
  #   target: src.agent.check.sql_tool.execute_sql

  # - name: cloud_transcription
  #   description: Transcribes audio into text
  #   target: src.agent.check.transcrip_tool.CloudTranscriptionTool
  #   params:
  #     endpoint_url: "https://api-inference.huggingface.co/models"
  #     api_key: ${HUG_API_KEY}
  #     model: "openai/whisper-large-v3"
  #     provider: "huggingface"
      
# agent:
  
#   math_agent:
#     description: Does basic arithmetic
#     llm: model
#     tools:
#       - name: add_numbers
#         description: Add two numbers together
#         target: src.agent.check.number.add_numbers

#       - name: multiply
#         description: Multiply two numbers
#         target: src.agent.check.number.multiply


  # weather_agent:
  #   description: Answers weather questions
  #   llm: model
  #   tools:
  #     - name: weather_tool
  #       description: Fetch live weather for a city
  #       target: src.agent.tool.weather.weather_tool



# method: "tool"

# max_steps: 5

# model:
#   path: "openrouter/meta-llama/llama-3.3-8b-instruct:free"
#   method: "litellm"   
#   api_key: ${OPENROUTER_API_KEY}
#   api_base: "https://openrouter.ai/api/v1" 
#   temperature: 0.7

# tools:
#   - name: add_numbers
#     description: Add two numbers together
#     target: src.agent.check.number.add_numbers   
#     inputs:
#       a:
#         type: int
#         description: First number
#       b:
#         type: int
#         description: Second number

#   - name: multiply
#     description: Multiply two numbers
#     target: src.agent.check.number.multiply     
#     inputs:
#       a:
#         type: int
#         description: First number
#       b:
#         type: int
#         description: Second number

#   - name: weather_tool
#     description: Fetch live weather for a given city using openweather api.
#     target: src.agent.tool.weather.weather_tool
#     inputs:
#       city:
#         type: string
#         description: The city name
#       units:
#         type: string
#         description: Units for temperature
#         nullable: true
=======

>>>>>>> 5f1e44bc6c582f6c8909ae10d382f00402a2d6a7
