tabular:
  idcolumn: null
  textcolumns: null
  content: false
  
llm:
  method: litellm
<<<<<<< HEAD
  path: openrouter/x-ai/grok-4-fast:free #path: openrouter/meta-llama/llama-3.3-8b-instruct:free
  api_key: ${OPENROUTER_API_KEY}
=======
  path: openrouter/meta-llama/llama-3.3-8b-instruct:free
  api_key: 
>>>>>>> 5f1e44bc6c582f6c8909ae10d382f00402a2d6a7
  api_base: https://openrouter.ai/api/v1
  temperature: 0.7

# llm:
#   method: transformers
#   path: D:/backend/ESAI/src/model/medgemma-4b-it
#   quantize: true
#   gpu: false

agent:

  conversation_agent:
    description: Agent that asks follow-up questions
    method: code
    max_iterations: 5
    tasks:
      default:
        prompt: |
          You are a friendly interviewer. Continue the conversation.
          Conversation so far:
          {text}
          Next question:
        
  math_agent:
    description: Does basic arithmetic
    max_iterations: 5
    method: tool
  
    tools:
      - name: add_numbers
        description: Add two numbers together
        target: src.agent.check.number.add_numbers

      - name: multiply
        description: Multiply two numbers
        target: src.agent.check.number.multiply

  weather_agent:
    description: Answers weather questions
    max_iterations: 5
    method: tool
    tools:
      - name: weather_tool
        description: Fetch live weather for a city
        target: src.agent.tool.weather.weather_tool

  voice_agent:
    
    method: "tool"
    max_iterations: 5
    tools:
      - name: speech_to_text
        description: Convert audio input to text
        target: src.agent.check.speech_text.speech
        provider: "fal-ai"
        api_key: ${HUG_API_KEY}

      - name: tex
  
  sql_agent:
    description: Generates and executes SQL queries against a database.
    max_iterations: 8
    method: tool # Tells the agent to use the tools defined below
    tools:
      - name: execute_sql
        description: Executes a SQL query against the database and returns the results.
        target: src.agent.check.sql_tool.execute_sql
     
  default_agent:
    max_iterations: 5
    method: code
    tools:
      - python
      - websearch
      - webview

